
export const REQUEST_CYCLE_LIST = "REQUEST_CYCLE_LIST"
export const SUCCESS_CYCLE_LIST = "SUCCESS_CYCLE_LIST"
export const ERROR_CYCLE_LIST = "ERROR_CYCLE_LIST"

export const REQUEST_CYCLE = "REQUEST_CYCLE"
export const SUCCESS_CYCLE = "SUCCESS_CYCLE"
export const ERROR_CYCLE = "ERROR_CYCLE"
